/**
 * GitHub integration utilities.
 *
 * Provides abstractions for GitHub API interactions used by the pipeline.
 * Uses Octokit-style patterns but can be adapted to any GitHub client.
 */

export interface GitHubLabel {
  name: string;
  color: string;
  description: string;
}

export const PIPELINE_LABELS: GitHubLabel[] = [
  { name: 'stage:pain', color: 'FF6B6B', description: 'Pain mining stage' },
  { name: 'stage:cluster', color: 'FFA07A', description: 'Clustering stage' },
  { name: 'stage:validate', color: 'FFD700', description: 'Validation stage' },
  { name: 'stage:competition', color: '98FB98', description: 'Competition research stage' },
  { name: 'stage:debate', color: '87CEEB', description: 'Bull/Bear/Customer debate stage' },
  { name: 'stage:judge', color: 'DDA0DD', description: 'Final judge stage' },
  { name: 'stage:complete', color: '90EE90', description: 'Stage completed' },
  { name: 'status:ready', color: 'BFE5BF', description: 'Ready to process' },
  { name: 'status:running', color: 'FFE4B5', description: 'Currently running' },
  { name: 'status:review', color: 'ADD8E6', description: 'Needs human review' },
  { name: 'status:passed', color: '006B3C', description: 'Passed gates' },
  { name: 'status:rejected', color: 'B22222', description: 'Rejected' },
  { name: 'status:approved', color: '228B22', description: 'Approved' },
  { name: 'status:error', color: 'FF0000', description: 'Error occurred' },
  { name: 'status:needs-evidence', color: 'FFA500', description: 'Needs more evidence' },
];

/**
 * Generate a unique branch name for a pipeline stage.
 */
export function generateStageBranch(runId: string, opportunityId: string, stage: string): string {
  return `pipeline/${runId.toLowerCase()}/${opportunityId.toLowerCase()}/${stage}`;
}

/**
 * Generate a PR title for a pipeline stage.
 */
export function generatePRTitle(runId: string, opportunityId: string, stage: string): string {
  return `[${runId}] ${stage}: ${opportunityId}`;
}

/**
 * Generate a PR body with required metadata.
 */
export function generatePRBody(params: {
  runId: string;
  opportunityId: string;
  stage: string;
  modelUsed: string;
  evidenceCount: number;
  gateStatus: string;
  artifacts: string[];
}): string {
  return [
    `## Pipeline Stage: ${params.stage}`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| Run ID | ${params.runId} |`,
    `| Opportunity ID | ${params.opportunityId} |`,
    `| Stage | ${params.stage} |`,
    `| Model Used | ${params.modelUsed} |`,
    `| Evidence Count | ${params.evidenceCount} |`,
    `| Gate Status | ${params.gateStatus} |`,
    `| Generated Artifacts | ${params.artifacts.join(', ')} |`,
    ``,
    `> This PR was automatically generated by the SaaS Ideas discovery pipeline.`,
  ].join('\n');
}

/**
 * Check if a branch name is system-generated.
 */
export function isSystemBranch(branchName: string): boolean {
  return branchName.startsWith('pipeline/');
}

/**
 * Validate that a file path is within allowed directories.
 */
export function isAllowedPath(filePath: string): boolean {
  const allowedPrefixes = ['research/', 'opportunities/', 'reports/', 'schemas/', 'config/'];
  return allowedPrefixes.some((prefix) => filePath.startsWith(prefix));
}

/**
 * Sanitize a string for use in branch/file names.
 */
export function sanitizeForGit(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100);
}
